from pathlib import Path
import re

src = Path('revision_20260922_round2/manuscript/supplement.md')
dst = Path('revision_20260923_jrmv/manuscript/supplement.md')
t = src.read_text(encoding='utf-8')

# The supplement keeps its own numbering, so the figures referenced from the main
# text are documented by file and regeneration path rather than re-embedded.
note = '''
## S0. Notes on displays shared with the main article

The main article carries six tables and five figures. The supplementary document keeps its own S numbering and does not repeat those displays. The five main figure files, with their vector sources and the scripts that regenerate each one from frozen outputs, are listed below. Every figure was written as vector PDF and SVG plus a 900 dpi PNG review raster, and a layout audit measured all text bounding boxes and failed on any collision.

| Main display | Vector file | PNG raster | Regeneration script |
| --- | --- | --- | --- |
| Figure 1 | figures/figure1_protocol.pdf | figures/figure1_protocol.png | scripts/build_figures_publication.py |
| Figure 2 | figures/figure2_four_cell.pdf | figures/figure2_four_cell.png | scripts/build_figures_publication.py |
| Figure 3 | figures/figure3_development_influence.pdf | figures/figure3_development_influence.png | scripts/build_figures_publication.py |
| Figure 4 | figures/figure4_development_domain.pdf | figures/figure4_development_domain.png | scripts/build_figures_publication.py |
| Figure 5 | figures/figure5_source_evidence.pdf | figures/figure5_source_evidence.png | scripts/build_figures_publication.py |

The main tables are regenerated by scripts/assemble_manuscript.py from the frozen comparison files, so no table value in the main article is transcribed by hand.
'''
marker = '## S1. Sampling frame, observation unit and recorded outcome'
i = t.index(marker)
t = t[:i] + note.strip() + '\n\n' + t[i:]
dst.write_text(t, encoding='utf-8')
print('supplement staged', len(t), 'chars', len(re.findall(r'^Table S\d+\.', t, re.M)), 'tables')
